document.writeln("<div id=\'a[[This.x]][[This.y]][[This.width]]\' style=\'position:absolute; top:[[This.y]]px; left:[[This.x]]px\'>");
document.writeln("<template>");
document.writeln("  <el-select v-model=\'value\' placeholder=\'请选择\' style=\'width:[[This.width]]\'>");
document.writeln("    <el-option");
document.writeln("      v-for=\'item in options\'");
document.writeln("      :key=\'item.value\'");
document.writeln("      :label=\'item.label\'");
document.writeln("      :value=\'item.value\'");
document.writeln("      :disabled=\'item.disabled\'>");
document.writeln("    </el-option>");
document.writeln("  </el-select>");
document.writeln("</template>");
document.writeln("</div>");
document.writeln("");
document.writeln("<script>");
document.writeln("var Main = {");
document.writeln("    data() {");
document.writeln("      return {");
document.writeln("        options: [{");
document.writeln("          value: \'选项1\',");
document.writeln("          label: \'黄金糕\',");
document.writeln("          disabled: false");
document.writeln("        }, {");
document.writeln("          value: \'选项2\',");
document.writeln("          label: \'双皮奶\',");
document.writeln("          disabled: true");
document.writeln("        }, {");
document.writeln("          value: \'选项3\',");
document.writeln("          label: \'蚵仔煎\'");
document.writeln("        }, {");
document.writeln("          value: \'选项4\',");
document.writeln("          label: \'龙须面\'");
document.writeln("        }, {");
document.writeln("          value: \'选项5\',");
document.writeln("          label: \'北京烤鸭\'");
document.writeln("        }],");
document.writeln("        value: \'\'");
document.writeln("      }");
document.writeln("    }");
document.writeln("  }");
document.writeln("var Ctor = Vue.extend(Main)");
document.writeln("new Ctor().$mount(\'#a[[This.x]][[This.y]][[This.width]]\')");
document.writeln("</script>");
